### ISSUE TITLE
코드 실행 오류

### ISSUE THREAD

**Issue by jong-hwan** [rlcode/reinforcement-learning-kr-v2#4]
![image](https://user-images.githubusercontent.com/63577714/83404883-59d4b680-a446-11ea-872e-8678d6af4739.png)
"1-grid-world/5-deep-sarsa/" 에 있는 스크립트가 실행하면 위와 같은 오류가 나옵니다.

**Comment by dnddnjs** [comment]
안녕하세요~! 
Wiki에 있는 설치 가이드를 따라하셨을 때 별 문제 없었나요? 
어떤 OS 였나요?

**Comment by j-hae1** [comment]
Window에서 다음과 동일한 오류가 뜹니다

**Comment by jong-hwan** [comment]
def call(self, x):
        x = tf.to_float(x)
        x = self.fc1(x)
        x = self.fc2(x)
        q = self.fc_out(x)
        return q

DeepSARSA클래스의 call 메소드 부분에 tf.to_float을 추가해서 해당 오류를 해결했습니다. :)
더불어 학습하면서 메모리가 계속 증가하기 때문에 학습과정에서 메모리를 잡아주는 코드가 필요할 것 같습니다.
